Description: "Test stack"

Resources:
  CodeBuildRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName:
          Fn::Sub: CodeBuildRole-${AWS::StackName}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "codebuild.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Path: /service-role/
        Policies:
          -
            PolicyName: "CodeBuildNestedCFNAccessPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "cloudformation:Get*"
                    - "cloudformation:Describe*"
                    - "cloudformation:List*"
                  Resource:
                    - Fn::Sub: arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/Test-${AWS::StackName}*
                # -
                #   Effect: "Allow"
                #   Action:
                #     - "codecommit:ListBranches"
                #     - "codecommit:ListRepositories"
                #     - "codecommit:BatchGetRepositories"
                #     - "codecommit:Get*"
                #     - "codecommit:GitPull"
                #   Resource:
                #     - Fn::Sub: arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CFNTemplateRepoName}
                #     - Fn::Sub: arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${ValidateResourcesRepoName}
                -
                  Effect: "Allow"
                  Action:
                    - "ec2:Describe*"
                    - "cloudformation:ValidateTemplate"
                    - "elasticloadbalancing:Describe*"
                    - "autoscaling:Describe*"
                    - "iam:Get*"
                    - "iam:List*"
                    - "logs:Describe*"
                    - "logs:Get*"
                    - "tag:Get*"
                  Resource:
                    - "*"
                -
                  Effect: "Allow"
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource:
                    - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
                -
                  Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                    - "s3:GetObject"
                    - "s3:GetObjectVersion"
                    - "s3:ListBucket"
                  Resource:
                    - Fn::Sub: arn:aws:s3:::codepipeline-${AWS::Region}-*
                    - Fn::Sub: arn:aws:s3:::nestedcfn-basestack-s3bucket-15snq7e488w06/*
                    - Fn::Sub: arn:aws:s3:::nestedcfn-basestack-s3bucket-15snq7e488w06

  BuildCopyCFNProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: BuildCopyCFN-${AWS::StackName}
      Description: Build to validate and copy CFN templates
      ServiceRole:
        Fn::GetAtt: [ CodeBuildRole, Arn ]
      Artifacts:
        Type: S3
        Location: nestedcfn-basestack-s3bucket-15snq7e488w06
        Name:
          Fn::Sub: BuildCopyCFN-${AWS::StackName}
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:7.0.0
        EnvironmentVariables:
          - Name: TEMPLATE_BUCKET
            Value: nestedcfn-basestack-s3bucket-15snq7e488w06
          - Name: TEMPLATE_PREFIX
            Value: codebuild
      Source:
        Type: GITHUB
        Auth:
          -
            Type: OAUTH
          # Resource:
        BuildSpec: buildspec.yml
        GitCloneDepth: 5
        InsecureSsl: true
        Location: https://github.com/mlhatfield/docker-encabulator.git
      TimeoutInMinutes: 15
      EncryptionKey:
        Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3
      Tags:
        - Key: Name
          Value:
            Fn::Sub: BuildCopyCFN-${AWS::StackName}
